AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Template using python3.8

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    # Important parameter to tweak, if too small ther service will always timeout
    MemorySize: 5000

Resources:
  {{package_name | to_pascal_case}}Function:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Events:
        {{package_name | to_pascal_case}}:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /predict
            Method: post
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerTag: python3.8-v1

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  {{package_name | to_pascal_case}}Api:
    Description: "API Gateway endpoint URL for Prod stage for function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/predict/"
  {{package_name | to_pascal_case}}Function:
    Description: "Lambda Function ARN"
    Value: !GetAtt {{package_name | to_pascal_case}}Function.Arn
  {{package_name | to_pascal_case}}FunctionIamRole:
    Description: "Implicit IAM Role created for function"
    Value: !GetAtt {{package_name | to_pascal_case}}FunctionRole.Arn
